--[[---------------------------------------------------------------------------
    Chocolatier Three: Character Asset Manifest
    This file tells the game which art assets exist for each character.
    Copyright (c) 2025 Michael Lane and Google Gemini AI.
--]]---------------------------------------------------------------------------

CharacterAssetManifest = {
    -- Main Characters (all have masks)
    main_alex = { png = true, mask = true, silhouette = true, w = 150, h = 230, silhouette_x = 20, silhouette_y = 115, list_x_offset = 2 },
    main_chas = { png = true, mask = true, silhouette = true, w = 172, h = 268, silhouette_x = 10, silhouette_y = 125, list_x_offset = 0 },
    main_deit = { png = true, mask = true, silhouette = true, w = 156, h = 260, silhouette_x = 20, silhouette_y = 115, list_x_offset = 2 },
    main_elen = { png = true, mask = false },
    main_evan = { png = true, mask = true, silhouette = true, w = 154, h = 258, silhouette_x = 20, silhouette_y = 116, list_x_offset = 4 },
    main_feli = { png = true, mask = true, silhouette = true, w = 160, h = 242, silhouette_x = 12, silhouette_y = 121, list_x_offset = 1 },
    main_jose = { png = true, mask = true, silhouette = true, w = 166, h = 284, silhouette_x = 9, silhouette_y = 141, list_x_offset = 2 },
    main_loud = { png = true, mask = true, silhouette = true, w = 172, h = 242, silhouette_x = 10, silhouette_y = 121, list_x_offset = 0 },
    main_sara = { png = true, mask = true, silhouette = true, w = 166, h = 252, silhouette_x = 10, silhouette_y = 116, list_x_offset = 2 },
    main_sean = { png = true, mask = true, silhouette = true, w = 164, h = 270, silhouette_x = 9, silhouette_y = 131, list_x_offset = 2 },
    main_tedd = { png = true, mask = true, silhouette = true, w = 168, h = 252, silhouette_x = 6, silhouette_y = 108, list_x_offset = 1 },
    main_whit = { png = true, mask = true, silhouette = true, w = 173, h = 252, silhouette_x = 8, silhouette_y = 110, list_x_offset = 1 },
    main_zach = { png = true, mask = true, silhouette = true, w = 144, h = 234, silhouette_x = 18, silhouette_y = 112, list_x_offset = 5 },
	
    -- Villains (all have masks)
    evil_bian = { png = true, mask = true, silhouette = true, w = 156, h = 224, silhouette_x = 20, silhouette_y = 121, list_x_offset = 2 },
    evil_kath = { png = true, mask = true, silhouette = true, w = 172, h = 254, silhouette_x = 7, silhouette_y = 110, list_x_offset = 0 },
    evil_wolf = { png = true, mask = true, silhouette = true, w = 156, h = 268, silhouette_x = 11, silhouette_y = 125, list_x_offset = 3 },
    evil_tyso = { png = true, mask = true, silhouette = true, w = 172, h = 262, silhouette_x = 10, silhouette_y = 121, list_x_offset = 0 },

    -- Shopkeepers & Market Keepers (all have masks)
	bag_marketkeep = { png = true, mask = true, silhouette = true, w = 151, h = 270, silhouette_x = 12, silhouette_y = 130, list_x_offset = 4 },
	bag_shopkeep = { png = true, mask = true, silhouette = true, w = 172, h = 270, silhouette_x = 10, silhouette_y = 135, list_x_offset = 0 },
	bag_towerkeep = { png = true, mask = true, silhouette = true, w = 173, h = 270, silhouette_x = 8, silhouette_y = 131, list_x_offset = 0 },
	bal_marketkeep = { png = true, mask = true, silhouette = true, w = 173, h = 256, silhouette_x = 10, silhouette_y = 115, list_x_offset = 0 },
	bal_shopkeep = { png = true, mask = true, silhouette = true, w = 166, h = 270, silhouette_x = 11, silhouette_y = 130, list_x_offset = 2 },
	bal_xxxkeep = { png = true, mask = true, silhouette = true, w = 172, h = 260, silhouette_x = 10, silhouette_y = 121, list_x_offset = 0 },
	bog_marketkeep = { png = true, mask = true, silhouette = true, w = 172, h = 268, silhouette_x = 7, silhouette_y = 125, list_x_offset = 0 },
	bog_plantationkeep = { png = true, mask = true, silhouette = true, w = 174, h = 266, silhouette_x = 8, silhouette_y = 128, list_x_offset = 1 },
	bog_shopkeep = { png = true, mask = true, silhouette = true, w = 142, h = 254, silhouette_x = 22, silhouette_y = 126, list_x_offset = 4 },
	cap_marketkeep = { png = true, mask = true, silhouette = true, w = 172, h = 220, silhouette_x = 10, silhouette_y = 121, list_x_offset = 0 },
	cap_shopkeep = { png = true, mask = true, silhouette = true, w = 163, h = 270, silhouette_x = 15, silhouette_y = 131, list_x_offset = 1 },
	dou_marketkeep = { png = true, mask = true, silhouette = true, w = 172, h = 256, silhouette_x = 8, silhouette_y = 113, list_x_offset = 0 },
	dou_plantationkeep = { png = true, mask = true, silhouette = true, w = 172, h = 254, silhouette_x = 10, silhouette_y = 111, list_x_offset = 0 },
	dou_shopkeep = { png = true, mask = true, silhouette = true, w = 192, h = 236, silhouette_x = 7, silhouette_y = 124, list_x_offset = -5 },
	hav_marketkeep = { png = true, mask = true, silhouette = true, w = 162, h = 262, silhouette_x = 10, silhouette_y = 123, list_x_offset = 2 },
	hav_plantationkeep = { png = true, mask = true, silhouette = true, w = 172, h = 270, silhouette_x = 7, silhouette_y = 128, list_x_offset = 0 },
	hav_shopkeep = { png = true, mask = true, silhouette = true, w = 156, h = 262, silhouette_x = 15, silhouette_y = 120, list_x_offset = 3 },
	kon_marketkeep = { png = true, mask = true, silhouette = true, w = 158, h = 256, silhouette_x = 10, silhouette_y = 118, list_x_offset = 3 },
	kon_plantationkeep = { png = true, mask = true, silhouette = true, w = 168, h = 256, silhouette_x = 10, silhouette_y = 118, list_x_offset = 1 },
	kon_shopkeep = { png = true, mask = true, silhouette = true, w = 172, h = 258, silhouette_x = 10, silhouette_y = 116, list_x_offset = 0 },
	lim_marketkeep = { png = true, mask = true, silhouette = true, w = 172, h = 270, silhouette_x = 10, silhouette_y = 131, list_x_offset = 0 },
	lim_shopkeep = { png = true, mask = true, silhouette = true, w = 172, h = 262, silhouette_x = 10, silhouette_y = 121, list_x_offset = 0 },
	mah_shopkeep = { png = true, mask = false },
	rey_marketkeep = { png = true, mask = false },
	rey_shopkeep = { png = true, mask = false },
	san_marketkeep = { png = true, mask = true, silhouette = true, w = 138, h = 258, silhouette_x = 21, silhouette_y = 114, list_x_offset = 5 },
	san_shopkeep = { png = true, mask = true, silhouette = true, w = 134, h = 252, silhouette_x = 29, silhouette_y = 133, list_x_offset = 16 },
	tok_marketkeep = { png = true, mask = true, silhouette = true, w = 170, h = 258, silhouette_x = 10, silhouette_y = 115, list_x_offset = 0 },
	tok_shopkeep = { png = true, mask = true, silhouette = true, w = 172, h = 262, silhouette_x = 10, silhouette_y = 121, list_x_offset = 0 },
	tor_factorykeep = { png = true, mask = true, silhouette = true, w = 164, h = 268, silhouette_x = 18, silhouette_y = 125, list_x_offset = 2 },
	tor_marketkeep = { png = true, mask = true, silhouette = true, w = 168, h = 268, silhouette_x = 11, silhouette_y = 126, list_x_offset = 1 },
	tor_shopkeep = { png = true, mask = true, silhouette = true, w = 162, h = 260, silhouette_x = 11, silhouette_y = 115, list_x_offset = 2 },
	ulu_hutkeep = { png = true, mask = true, silhouette = true, w = 152, h = 250, silhouette_x = 16, silhouette_y = 131, list_x_offset = 3 },
	wel_marketkeep = { png = true, mask = true, silhouette = true, w = 156, h = 250, silhouette_x = 21, silhouette_y = 130, list_x_offset = 2 },
	wel_shopkeep = { png = true, mask = true, silhouette = true, w = 134, h = 215, silhouette_x = 20, silhouette_y = 126, list_x_offset = 8 },
	zur_factorykeep = { png = true, mask = true, silhouette = true, w = 178, h = 250, silhouette_x = 6, silhouette_y = 116, list_x_offset = -2 },
	zur_marketkeep = { png = true, mask = true, silhouette = true, w = 172, h = 264, silhouette_x = 8, silhouette_y = 123, list_x_offset = 0 },
	zur_shopkeep = { png = true, mask = true, silhouette = true, w = 170, h = 260, silhouette_x = 11, silhouette_y = 118, list_x_offset = 0 },

    -- Other Characters (without masks - no silhouette overrides needed)
    announcer = { png = true, mask = false },
    bag_bldg2keep = { png = true, mask = false },
    bel_hutkeep = { png = true, mask = false },
    bog_churchkeep = { png = true, mask = false },
    bog_mountainkeep = { png = true, mask = false },
    cap_mountainkeep = { png = true, mask = false },
    dou_bldg1keep = { png = true, mask = false },
    fal_xxxkeep = { png = true, mask = false },
    gob_xxxkeep = { png = true, mask = false },
    hav_casinokeep = { png = true, mask = false },
    hav_hotelkeep = { png = true, mask = false },
    kon_bldg2keep = { png = true, mask = false },
    las_casinokeep = { png = true, mask = false },
    las_marketkeep = { png = true, mask = false },
    lim_churchkeep = { png = true, mask = false },
    lim_plazakeep = { png = true, mask = false },
    rey_xxxxkeep = { png = true, mask = false },
    san_barkeep = { png = true, mask = false },
    tan_hotelkeep = { png = true, mask = false },
    tan_portkeep = { png = true, mask = false },
    tok_mountainkeep = { png = true, mask = false },
    tok_palacekeep = { png = true, mask = false },
    tok_stationkeep = { png = true, mask = false },
    tok_towerkeep = { png = true, mask = false },
    tor_bldg1keep = { png = true, mask = false },
    tor_bldg2keep = { png = true, mask = false },
    trav_01 = { png = true, mask = false },
    trav_02 = { png = true, mask = false },
    trav_03 = { png = true, mask = false },
    trav_04 = { png = true, mask = false },
    trav_05 = { png = true, mask = false },
    trav_06 = { png = true, mask = false },
    trav_07 = { png = true, mask = false },
    trav_08 = { png = true, mask = false },
    trav_09 = { png = true, mask = false },
    trav_10 = { png = true, mask = false },
    trav_11 = { png = true, mask = false },
    ulu_rockkeep = { png = true, mask = false },
    wel_bldg1keep = { png = true, mask = false },
    zur_bankkeep = { png = true, mask = false },
    zur_mountainkeep = { png = true, mask = false },
    zur_riverkeep = { png = true, mask = false },
    zur_schoolkeep = { png = true, mask = false },
    zur_stationkeep = { png = true, mask = false },
    zur_towerkeep = { png = true, mask = false },
}