--[[---------------------------------------------------------------------------
	Chocolatier Three: Development Menu - Quest Variables Editor
	Copyright (c) 2008 Big Splash Games, LLC. All Rights Reserved.
	Modified (c) 2026 Michael Lane and Google Gemini AI.
--]]---------------------------------------------------------------------------

-------------------------------------------------------------------------------
-- Logic Action Handlers
-------------------------------------------------------------------------------

-- Interrogates the active player profile and alters specific hidden quest progress flags
local function ChangeVariable(varName)
	local originalValue = Player.questVariables[varName] or 0
	
	DisplayDialog { 
		"dev/dev_enter_amount.lua", 
		prompt = "Enter new value for '" .. varName .. "':",
		initialValue = tostring(originalValue),
		
		onOk = function(value)
			if value == 0 then value = nil end
			
			Player.questVariables[varName] = value
			DebugOut("DEV", string.format("Quest Variable Overridden -> '%s' (Old: %s | New: %s)", varName, tostring(originalValue), tostring(value)))
			
			-- Update the label dynamically so the dev menu reflects the new status
			local updatedValue = Player.questVariables[varName] or 0
			local newLabel = "#" .. varName .. ": <b>" .. tostring(updatedValue) .. "</b>"
			SetLabel("dev_" .. varName, newLabel)
		end
	}
end

-------------------------------------------------------------------------------
-- UI Construction
-------------------------------------------------------------------------------

local h = devMenuStyle.font[2]
local w = 150
local x = 0
local y = 2 * h

local items = {}

local function AddItem(i)
	table.insert(items, i)
	y = y + h
	if y > 400 then
		x = x + w
		y = h
	end
end

-- Iterate the global registry of all tracking variables generated by the quest parser
for _, name in ipairs(_AllVariableNames) do
	local value = Player.questVariables[name] or 0
	local label = "#" .. name .. ": <b>" .. tostring(value) .. "</b>"
	local temp = name
	
	AddItem(Button { 
		x = x, y = y, w = w, h = h, 
		name = "dev_" .. name, label = label, 
		command = function() ChangeVariable(temp) end 
	})
end

MakeDialog
{
	name = "dev_vars",
	BSGWindow { 
		x = gDialogTable.x, y = gDialogTable.y, w = w, h = h, fit = true, color = { 1, 1, 1, 0.8 }, SetStyle(devMenuStyle),
		
		Button { x = 0, y = 0, w = w, h = h, label = "#<b>CLOSE</b>", default = true, cancel = true, close = true },
		TightText { x = 0, y = h, w = 2*w, h = h, label = "#<b>Click a variable to manually alter its numeric state.</b>" },
		TightText { x = 0, y = h, w = 3*w, h = h },
		
		Group(items),
	},
}